==========================================
SLURM_JOB_ID = 7964037
SLURM_JOB_NODELIST = d11-16
TMPDIR = /tmp/SLURM_7964037
==========================================
/home1/dpwani/.local/lib/python3.9/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
/home1/dpwani/.local/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
| TRAIN SET | Epoch [01/30], Step [0000/1733], Loss: 6.9131| TRAIN SET | Epoch [01/30], Step [0001/1733], Loss: 6.8742Traceback (most recent call last):
  File "/home1/dpwani/vqa_baseline/visual_question_answering/train.py", line 220, in <module>
    main(args)
  File "/home1/dpwani/vqa_baseline/visual_question_answering/train.py", line 93, in main
    output = model(image, question)      # [batch_size, ans_vocab_size=1000]
  File "/home1/dpwani/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/dpwani/vqa_baseline/visual_question_answering/models.py", line 77, in forward
    img_feature = self.img_encoder(img)                     # [batch_size, embed_size]
  File "/home1/dpwani/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/dpwani/vqa_baseline/visual_question_answering/models.py", line 29, in forward
    img_feature = self.model(image)                  # [batch_size, vgg16(19)_fc=4096]
  File "/home1/dpwani/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/dpwani/.local/lib/python3.9/site-packages/torchvision/models/vgg.py", line 43, in forward
    x = self.features(x)
  File "/home1/dpwani/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/dpwani/.local/lib/python3.9/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home1/dpwani/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/dpwani/.local/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home1/dpwani/.local/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
  File "/home1/dpwani/.local/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 129915) is killed by signal: Killed. 
/var/spool/slurm/d/job7964037/slurm_script: line 14: 129895 Segmentation fault      python train.py --model_name="vqa_1_"
slurmstepd: error: Detected 3 oom-kill event(s) in StepId=7964037.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
